-- OPERATORS: USED TO PERFORM AN OPERATIONS BTW TWO OR MORE THAN TWO OPERANDS.
-- ARITHMETIC OPERATORS: FOR ARITHMETIC OPERATION

USE SQL_JUNE;

SELECT AGE+10 FROM STUDENT;
SELECT AGE-10 FROM STUDENT;
SELECT AGE*10 FROM STUDENT;
SELECT AGE/10 FROM STUDENT;
SELECT AGE%10 FROM STUDENT;

show tables;
select * from student;
-- COMPARISON OPERATORS: COMPARE VALUES
SELECT * FROM STUDENT WHERE AGE<25;
SELECT * FROM STUDENT WHERE AGE>25;
SELECT * FROM STUDENT WHERE AGE<=25;
SELECT * FROM STUDENT WHERE AGE>=25;
SELECT * FROM STUDENT WHERE AGE=25;
SELECT * FROM STUDENT WHERE AGE != 25; -- not equals to
SELECT * FROM STUDENT WHERE AGE <> 25; -- not equals to

-- LOGICAL OPERATORS: USED TO PERFORM LOGICAL OPERATIONS
-- AND,OR,NOT,IN,BETWEEN,LIKE,ANY,SOME,ALL,EXISTS

-- AND:

SELECT * FROM STUDENT WHERE GENDER = 'MALE' AND AGE>25;

-- OR
SELECT * FROM STUDENT WHERE GENDER = 'MALE' OR AGE>25;

SELECT * FROM STUDENT WHERE AGE>23 AND AGE<=27;

-- NOT 
SELECT * FROM STUDENT WHERE NOT GENDER='MALE';

-- IN
SELECT * FROM STUDENT WHERE AGE NOT IN (20,24,27);
SELECT * FROM STUDENT WHERE AGE  IN (20,24,27);

-- BETWEEN:
SELECT * FROM STUDENT WHERE AGE BETWEEN 24 AND 27;
SELECT * FROM STUDENT WHERE NAME BETWEEN 'R' AND 'T';

-- like: used in a where clause to search for a specified pattern in 
-- column.
-- IT IS ALSO KNOWN AS WILDCARD OPERATOR.
-- "%" AND "_" are known as wild card characters.
use sql_june;
select * from student;

select * from student 
where name like "s%";

select * from student 
where name like "%A";

select * from student 
where name like "_a%";

select * from student
where name like "%a_" and gender = "male";

select * from student where city like"g%a";

select * from student;

-- ORDER BY: USED TO SORT THE RESULT-SET IN ASCENDING OR
-- IN DESCENDING ORDER.
-- BY DEFAULT IT CONSIDER IN ASCENDING ORDER.
-- FOR ASCENDING WE USE "ASC" AND FOR DESCENDING "DESC".

SELECT * FROM STUDENT ORDER BY AGE;
SELECT * FROM STUDENT ORDER BY CITY;
SELECT * FROM STUDENT ORDER BY AGE DESC;
SELECT * FROM STUDENT ORDER BY AGE ASC,CITY DESC;
SELECT * FROM STUDENT ORDER BY CITY ASC,AGE DESC;

-- LIMIT: USED TO SPECIFY THE NO OF ROWS/RECORDS TO RETURN

SELECT * FROM STUDENT;
SELECT * FROM STUDENT LIMIT 3;

-- RETRIEVE THE DATA OF THE STUDENT WHICH HAS HIGHEST AGE
SELECT * FROM STUDENT ORDER BY AGE DESC LIMIT 1;

SELECT * FROM STUDENT ORDER BY AGE DESC LIMIT 1;

-- RETRIEVE THE DATA OF THE STUDENT WHICH HAS 2ND HIGHEST AGE
SELECT * FROM STUDENT ORDER BY AGE DESC LIMIT 1,1;

SELECT * FROM STUDENT ORDER BY AGE DESC LIMIT 2,1;
-- LIMIT 1,2 : 1 ROW SKIP KRKE 2 ROW SHOW KARTA HAI
SELECT * FROM STUDENT;
SELECT * FROM STUDENT ORDER BY AGE DESC LIMIT 1 OFFSET 1;
-- LIMIT 1 OFFSET(SKIP) 2: 1 ROW SHOW KRTA HAI 2 ROW SKIP KRKE

-- ALIASING: USED TO GIVE THE TEMPORARY NAME TO A FIELD

SELECT ID+AGE AS TOTAL_AGE FROM STUDENT;

SELECT NAME AS NAAM, AGE AS UMAR FROM STUDENT;

-- AGGREGATE FUNCTIONS:
-- SUM(),MIN(),MAX(),AVG(),COUNT()

-- SUM():
SELECT SUM(AGE) as total_age FROM STUDENT;

-- min():
SELECT min(AGE) as min_age FROM STUDENT;

-- max():
SELECT max(AGE) as max_age FROM STUDENT;

-- avg():
SELECT avg(AGE) as avg_age FROM STUDENT;

-- count():
SELECT count(gender) as total_student FROM STUDENT;

USE SQL_JUNE;
-- STRING MANIPULATION FUNCTIONS:
-- USED TO MANIPULATE THE STRING VALLUES.

-- LENGTH() :RETURNS THE LENGTH OF THE STRING
SELECT * FROM STUDENT;

SELECT NAME,LENGTH(NAME) FROM STUDENT;

-- LOWER(): USED TO CONVERT IN THE LOWER CASE
SELECT LOWER(NAME) FROM STUDENT;

-- UPPER(): USED TO CONVERT IN THE UPPER CASE
SELECT UPPER(NAME) FROM STUDENT;

-- SUBSTRING()/MID(): USED TO EXTRACT CHARACTERS FORM A TEXT FIELD.
-- SYNTAX: SUBSTRING(COL_NAME,START_POSITION,LENGTH)

SELECT SUBSTRING(NAME,1,2) FROM STUDENT;
SELECT SUBSTRING(NAME,1,3) FROM STUDENT;
SELECT SUBSTRING(NAME,-3,3) FROM STUDENT;
SELECT SUBSTRING(NAME,-3,2) FROM STUDENT;

SELECT SUBSTRING(NAME,-3) FROM STUDENT;
SELECT SUBSTRING(NAME,2) FROM STUDENT;

SELECT MID(NAME,2) FROM STUDENT;
SELECT MID(NAME,-2) FROM STUDENT;

-- LOCATE(): FINDS A SUBSTRING WITHIN A TEXT FIELD.
-- SYNTAX: LOCATE(SUBSTRING,COL_NAME,START_POS)
SELECT NAME,LOCATE("A",NAME,1) FROM STUDENT;
SELECT NAME,LOCATE("A",NAME) FROM STUDENT;


SELECT NAME,LOCATE("A",NAME,LOCATE("A",NAME,1)+1) FROM STUDENT;

-- REPLACE(): USE TO REPLACE THE SUBSTRING BY 
-- NEW SUBSTRING IN THE TEXT FIELD
-- SYNTAX(COL_NAME,OLD_TXT,NEW_TXT)
-- CASE SENSITIVE

SELECT * FROM STUDENT;
SELECT NAME,REPLACE(NAME,"a","Z") FROM STUDENT;
SELECT NAME,REPLACE(NAME,"SHAYAM","RAMAAAAA") FROM STUDENT;

-- CONCAT: USED TO MERGE TWO OR MORE THAN TWO STRING
-- SYNTAX: CONCAT(TEXT1,TEXT2,TEXT3,...)
SELECT * FROM STUDENT;
SELECT CONCAT(NAME,CITY) FROM STUDENT;
SELECT CONCAT(NAME," , ",CITY) AS NAME_CITY FROM STUDENT;

SELECT CONCAT(ID," ",AGE) FROM STUDENT;

SELECT CONCAT_WS(",",ID,NAME,AGE,CITY,GENDER) FROM STUDENT;

-- TRIM(): USED TO REMOVE UNWANTED SPACES(LAGGING OR LEADING SPACES)
SELECT TRIM(NAME) FROM STUDENT;

SELECT LTRIM(NAME) FROM STUDENT;
SELECT RTRIM(NAME) FROM STUDENT;

-- REVERSE()
SELECT REVERSE(NAME) FROM STUDENT;

-- REPEAT()
-- SELECT REPEAT(AGE,3) FROM STUDENT;
-- SELECT REPEAT("RAM",10);


SELECT * from student;
alter table student
add column full_name varchar(50);

update student
set full_name = concat_ws(" ",name,"kumar sharma");

set sql_safe_updates=0;

-- SUBSTRING_INDEX(): used to extract the data based on the deilmiter
select SUBSTRING_INDEX(full_name," ",1) from student;

select SUBSTRING_INDEX(full_name," ",-1) from student;

select substring_index(SUBSTRING_INDEX(full_name," ",-2)," ",1) from student;

-- date data types:
-- DATE: YYYY-MM-DD
-- TIME: HH:MI:SS
-- DATETIME: YYYY-MM-DD HH:MI:SS
-- TIMESTAMP: YYYY-MM-DD HH:MI:SS
-- YEAR: YYYY OR YY

SELECT * FROM STUDENT;

ALTER TABLE STUDENT
ADD COLUMN DOB DATE;

UPDATE STUDENT 
SET DOB= "1990-12-12";

UPDATE STUDENT 
SET DOB= "1990-09-09" WHERE AGE>25;

SELECT * FROM STUDENT;

-- DATE FUNCTIONS;

-- NOW(): RETURNS THE CURRENT DATE AND TIME
SELECT NOW();

-- CURDATE(): RETURNS THE CURRENT DATE ONLY
SELECT CURDATE();

-- CURTIME(): RETURNS THE CURRENT TIME ONLY
SELECT CURTIME();

SELECT * FROM STUDENT;

-- YEAR
SELECT YEAR(DOB) FROM STUDENT;

-- MONTH
SELECT MONTH(DOB) FROM STUDENT;

-- DAY
SELECT DAY(DOB) FROM STUDENT;

-- DAYNAME
SELECT DAYNAME(DOB) FROM STUDENT;

-- MONTHNAME
SELECT MONTHNAME(DOB) FROM STUDENT;

-- WEEK
SELECT WEEK(DOB) FROM STUDENT;

SELECT DAYNAME(NOW());
-- HOUR
SELECT HOUR(NOW()) FROM STUDENT;

-- EXTRACT(); USED TO EXTRACT A SPECIFIC PART FROM A DATE/DATETIME/TIME COLUMN.

SELECT EXTRACT(YEAR FROM DOB) FROM STUDENT;

-- DATE_ADD(): USED TO ADD THE SPECIFIC(LIKE MON,YEAR) INTERVAL IN THE DATE COLUMN
SELECT * FROM STUDENT;
SELECT DATE_ADD(DOB, INTERVAL 10 DAY) FROM STUDENT;
SELECT DATE_ADD(DOB, INTERVAL 10 MONTH) FROM STUDENT;

SELECT DATE_ADD(DATE_ADD(DOB, INTERVAL 1 YEAR), INTERVAL 2 MONTH) FROM STUDENT;

SELECT DATE_ADD(DOB, INTERVAL -12 YEAR) FROM STUDENT;

SELECT DATE_ADD(DOB, INTERVAL 24 HOUR) FROM STUDENT;

-- DATE_SUB(): USED TO SUBTRACT THE SPECIFIC(LIKE MON,YEAR) INTERVAL IN THE DATE COLUMN
SELECT * FROM STUDENT;
SELECT DATE_SUB(DOB, INTERVAL 10 DAY) FROM STUDENT;
SELECT DATE_SUB(DOB, INTERVAL 10 MONTH) FROM STUDENT;

SELECT DATE_SUB(DATE_SUB(DOB, INTERVAL 1 YEAR), INTERVAL 2 MONTH) FROM STUDENT;

SELECT DATE_SUB(DOB, INTERVAL -12 YEAR) FROM STUDENT;

SELECT DATE_SUB(DOB, INTERVAL 24 HOUR) FROM STUDENT;


use sql_june;

alter table student
add column cur_date date;

set sql_safe_updates=0;

update student
set cur_date = curdate();

select * from student;

-- datediff(): used to calculate the difference between 2 date (in days)

select ROUND(datediff(cur_date,dob)/365.25,0) from student;
select CEIL(datediff(cur_date,dob)/365.25) from student;
select FLOOR(datediff(cur_date,dob)/365.25) from student;

SELECT * FROM STUDENT;

-- DATE_FORMAT():
/* USED TO FORMAT A DATE/DATETIME VALUE INTO A SPECIFIC FORMAT.
IT ALLOWS US TO CONVERT A DATE/DATETIME VALUE TO A FORMATTED STRING.

ALL FORMATTING TYPE:
1. "%Y" = 4 digit year
2. "%y" = 2 digit year
3. "%M" = month name
4. "%m" = numeric month (2 digit )
5. "%c" =  numeric month (1 or 2 digit)
6. "%d" = day of month ( 2 digit)
7. "%b" = abbreviated month name (eg. Jan)
8. "%W" = weekday name (eg. sunday)
9. "%a" = abbreviated day name(eg. sun)
10. "%H" = Hour (00-23 format)
11. "%h" or "%I" = Hour (01-12)
12. "%l" = Hour (1-12)
13. "%i"  = minutes(00-59)
14. "%s" = seconds
15. "%p" = AM/pm
*/


select dob,date_format(dob,"%d-%m-%Y") as formatted_date from student;
select dob,date_format(dob,"%d-%M-%Y") as formatted_date from student;
select dob,date_format(dob,"%d-%b-%Y") as formatted_date from student;
select dob,date_format(dob,"%d-%W-%b-%b-%Y") as formatted_date from student;

alter table student
add column formatted_date varchar(100);

select * from student;

update student
set formatted_date = date_format(dob,"%d-%b-%y , %W, %h-%i-%s %p");















